
/* RESOLVENDO O EXERCiCIO */
	CREATE DATABASE LIVRARIA;

/* CONECTANDO A UM BANCO */
	USE LIVRARIA;
	
/* CRIANDO A TABELA LIVROS */
	CREATE TABLE LIVROS(
		LIVRO VARCHAR(100),
		AUTOR VARCHAR(100),
		SEXO CHAR(1),
		PAGINAS INT(5),
		EDITORA VARCHAR(30),
		VALOR FLOAT(10,2),
		UF CHAR(2),
		ANO INT(4)
	);
	
/* VERIFICANDO OS BANCOS */
	SHOW DATABASES;

/* SEED DO DA TABELA LIVROS */
INSERT INTO LIVROS VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78,'RJ',2018);
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150,'RJ',2019);
INSERT INTO LIVROS VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78,'ES',2011);
INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130,'RS',2018);
INSERT INTO LIVROS VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56,'SP',2017);

/* 1 - TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/* 2 - TRAZER O NOME DO LIVRO E O NOME DA EDITORA*/
SELECT LIVRO, EDITORA FROM LIVROS;

/* 3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADO POR AUTORES DO SEXO MASCULINO */
SELECT LIVRO, UF FROM LIVROS WHERE SEXO = 'M';
SELECT AUTOR, SEXO, LIVRO, UF FROM LIVROS WHERE SEXO = 'M';

/* 4 - TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO.*/
SELECT LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';
SELECT AUTOR, LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';

/* 5 – TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO.*/
SELECT LIVRO, VALOR FROM LIVROS WHERE UF = 'SP';
SELECT UF, LIVRO, VALOR FROM LIVROS WHERE UF = 'SP';

/* 6 – TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO (QUESTÃO DESAFIO).*/
SELECT AUTOR, SEXO FROM LIVROS WHERE SEXO = 'M' AND UF = 'SP' OR UF = 'RJ'; #ERRADO

