-- MODELAGEM DE BANCO DE DADOS MER

-- 41 - PRIMEIRA FORMA NORMAL

/*
	1ª REGRA
		TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA
		VETOR= [VERMELHO, VERDE, AZUL, LARANJA]
	
	2ª REGRA
		TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA
		CAMPO MULTIVALORADO= "Rua sem nome, Jardim, Juaze, CE"
	3ª REGRA
		TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
		TODO O REGISTRO COMO SENDO UNICO.
		ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.
*/