/* Aula 43 e 44  Modelo Lógico para Físico */

CREATE DATABASE COMERCIO;

SHOW DATABASES;

USE COMERCIO;

SHOW TABLES;

CREATE TABLE CLIENTE (
	ID_CLIENTE BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    SEXO ENUM ('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ENDERECO(
	ID_ENDERECO BIGINT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2)
);

CREATE TABLE TELEFONE(
	ID_TELEFONE BIGINT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL
);














