
CREATE DATABASE COMERCIO;
DROP DATABASE COMERCIO;

SHOW DATABASES;

USE COMERCIO;

SHOW TABLES;

CREATE TABLE TB_CLIENTE (
	ID_CLIENTE BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    SEXO ENUM ('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE
);
DESC TB_CLIENTE;
DROP TABLE TB_CLIENTE;

CREATE TABLE TB_ENDERECO(
	ID_ENDERECO BIGINT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2),
    ID_CLIENTE BIGINT UNIQUE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);
DESC TB_ENDERECO;
DROP TABLE TB_ENDERECO;

CREATE TABLE TB_TELEFONE(
	ID_TELEFONE BIGINT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE BIGINT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);
DESC TB_TELEFONE;
DROP TABLE TB_TELEFONE;

INSERT INTO TB_CLIENTE VALUES ( NULL, 'JOÃO','00000000001', 'M', 'JOÃO@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CARLA','00000000002', 'F', 'CARLA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'ANA','00000000003', 'F', 'ANA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CLARA','00000000004', 'M', 'CLARA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'JORGE','00000000005', 'M', 'JORGE@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CELIA','00000000006', 'F', 'CELIA@GMAIL.COM' );

SELECT * FROM TB_CLIENTE;

INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA PARAGUAÇU', 'CENTRO', 'SÃO PAULO','SP',1);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA EUCLIDES DA CUNHA','JARDIM', 'NOVA OLINDA','CE',5);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA PADRE CICERO', 'TRIANGULO', 'JUAZEIRO DO NORTE','CE',6);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA DAS  DORES', 'ALCARIAS', 'RIO DE JANEIRO','RJ',4);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA MONTES CLOAROS', 'CENTRO', 'RECIFE','PE',3);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA EMILIO SANTOS', 'PEDRINHAS', 'OURICURI','PE',2);

SELECT * FROM TB_ENDERECO;

INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '1867165464', 5);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '5645646546', 5);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '6156541564', 1);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '6574186787', 2);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '1454545442', 1);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '6541616416', 3);
INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '4556674646', 3);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '4444545646', 1);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '7154545454', 5);
INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '4154641646', 2);

SELECT * FROM TB_TELEFONE;

/* PROJEÇÃO */
SELECT 2 + 4 AS SOMA;

/* SELEÇÃO */
SELECT NOME, SEXO, EMAIL
FROM TB_CLIENTE 
WHERE SEXO = 'F';

SELECT NUMERO
FROM TB_TELEFONE
WHERE TIPO = 'CEL';

/* JUNÇÃO - INNER JOIN */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM TB_CLIENTE
	INNER JOIN TB_ENDERECO
	ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECO.ID_CLIENTE;

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM TB_CLIENTE
INNER JOIN TB_TELEFONE
ON TB_CLIENTE.ID_CLIENTE = TB_TELEFONE.ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */

SELECT
	C.NOME,
	C.SEXO,
	E.BAIRRO,
	E.CIDADE,
	T.TIPO,
	T.NUMERO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE;

/* 
	DML - DATA MANIPULATION LENGUAGE
    DDL - DATA DEFINITION LENGUAGE
    DCL - DATA CONTROL LENGUAGE
    TCL - TRANSACTION CONTROL LENGUAGE
    
 */

/* DML - DATA MANIPULATION LENGUAGE */

INSERT INTO TB_CLIENTE VALUES ( NULL, 'PAULA','1767665454', 'M', 'PAULA@GMAIL.COM');
SELECT * FROM TB_CLIENTE;
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA CATARINA', 'ALVORADA', 'NITEROI','RJ',7);

/* FILTROS */
SELECT * FROM TB_CLIENTE
WHERE SEXO = 'F';

/* UPDATE */
UPDATE TB_CLIENTE
SET SEXO = 'F'
WHERE ID_CLIENTE = '7';

/* DELETE */

INSERT INTO TB_CLIENTE VALUES ( NULL, 'XXXX','0000000', 'M', 'XXX@GMAIL.COM');

SELECT * FROM TB_CLIENTE;

DELETE FROM TB_CLIENTE
WHERE ID_CLIENTE = '13';

/* DDL - DATA DEFINITION LENGUAGE */
CREATE TABLE TB_PRODUTO(
	ID_PRODUTO BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRECO INT
);

DESC TB_PRODUTO;

/* MODIFICANDO A ESTRUTURA DA TABELA */

/* CHANGE ALTERA NOME E TIPO  */
ALTER TABLE TB_PRODUTO
CHANGE PRECO VALOR_UNITARIO DECIMAL(10,2) NOT NULL;

/* MODIFY ALTERA TIPO */
ALTER TABLE TB_PRODUTO
MODIFY NOME VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNA NA TABELA */
ALTER TABLE TB_PRODUTO
ADD PESO DECIMAL(10,2);

ALTER TABLE TB_PRODUTO
ADD PESO DECIMAL(10,2)
AFTER NOME;

ALTER TABLE TB_PRODUTO
ADD PESO DECIMAL(10,2)
FIRST;

/* DELETANDO COLUNA */
ALTER TABLE TB_PRODUTO
DROP COLUMN PESO;

/* EXERCICIOS DML */
INSERT INTO TB_CLIENTE VALUES ( NULL, 'JOÃO','00000000001', 'M', 'JOÃO@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CARLA','00000000002', 'F', 'CARLA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'ANA','00000000003', 'F', 'ANA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CLARA','00000000004', 'M', 'CLARA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'JORGE','00000000005', 'M', 'JORGE@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'CELIA','00000000006', 'F', 'CELIA@GMAIL.COM' );
INSERT INTO TB_CLIENTE VALUES ( NULL, 'LUCIA','00000000007', 'F', 'LUCIA@GMAIL.COM' );

INSERT INTO TB_CLIENTE VALUES ( NULL, 'XXX','0000004545', 'F', 'XXX@GMAIL.COM' );

DELETE FROM TB_CLIENTE
WHERE ID_CLIENTE = '8';

INSERT INTO TB_CLIENTE VALUES(NULL,'FLAVIO','4657765','M','FLAVIO@IG.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'ANDRE','7687567','M','ANDRE@GLOBO.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'GIOVANA','0876655','F','GIOVANA@GMAIL.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'KARLA','545676778','M','KARLA@GMAIL.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'DANIELE','43536789','M','DANIELE@GMAIL.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'LORENA','774557887','M',NULL);
INSERT INTO TB_CLIENTE VALUES(NULL,'EDUARDO','54376457','M',NULL);
INSERT INTO TB_CLIENTE VALUES(NULL,'ANTONIO','12436767','F','ANTONIO@IG.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'ANTONIO','3423565','M','ANTONIO@UOL.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'ELAINE','32567763','M','ELAINE@GLOBO.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'CARMEM','787832213','M','CARMEM@IG.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'ADRIANA','88556942','F','ADRIANA@GMAIL.COM');
INSERT INTO TB_CLIENTE VALUES(NULL,'JOICE','55412256','F','JOICE@GMAIL.COM');

SELECT * FROM TB_CLIENTE;

INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA PARAGUAÇU', 'CENTRO', 'SÃO PAULO','SP',1);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA EUCLIDES DA CUNHA','JARDIM', 'NOVA OLINDA','CE',2);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA PADRE CICERO', 'TRIANGULO', 'JUAZEIRO DO NORTE','CE',3);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA DAS  DORES', 'ALCARIAS', 'RIO DE JANEIRO','RJ',4);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA MONTES CLOAROS', 'CENTRO', 'RECIFE','PE',5);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA EMILIO SANTOS', 'PEDRINHAS', 'OURICURI','PE',6);
INSERT INTO TB_ENDERECO VALUES (NULL, 'RUA ERMINIO', 'SERRA', 'ALTOS','PB',7);

INSERT INTO TB_ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO TB_ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO TB_ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO TB_ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO TB_ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

SELECT * FROM TB_ENDERECO;
/* CADASTRE TELEFONES PARA OS CLIENTES */

INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '1867165464', 1);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '5645646546', 2);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '6156541564', 3);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '6574186787', 4);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '1454545442', 5);
INSERT INTO TB_TELEFONE VALUES (NULL, 'CEL', '6541616416', 6);
INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '4556674646', 7);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '4444545646', 2);
INSERT INTO TB_TELEFONE VALUES (NULL, 'COM', '7154545454', 5);
INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '4154641646', 3);
INSERT INTO TB_TELEFONE VALUES (NULL, 'RES', '4154641600', 7);

INSERT INTO TB_TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TB_TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TB_TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TB_TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TB_TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TB_TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TB_TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TB_TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TB_TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TB_TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TB_TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TB_TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TB_TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TB_TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TB_TELEFONE VALUES(NULL,'COM','44522578',20);

SELECT * FROM TB_TELEFONE;

/* RELATORIO GERAL DE TODOS OS CLIENTES */

DESC TB_CLIENTE;
DESC TB_ENDERECO;
DESC TB_TELEFONE;

SELECT C.ID_CLIENTE, C.NOME, C.CPF, C.SEXO, C.EMAIL, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE;

/* RELATORIO DE HOMENS */

SELECT C.ID_CLIENTE, C.NOME, C.CPF, C.SEXO, C.EMAIL, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

/* ATUALIZANDO REGISTROS */
SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN (4, 12, 13, 18, 19);

UPDATE TB_CLIENTE SET SEXO = 'F'
WHERE ID_CLIENTE IN (4, 12, 13, 18, 19);


/* RELATORIO DE MULHERES */

SELECT C.ID_CLIENTE, C.NOME, C.CPF, C.SEXO, C.EMAIL, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

/* ATUALIZANDO REGISTROS */
SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN (16);

UPDATE TB_CLIENTE SET SEXO = 'M'
WHERE ID_CLIENTE IN (16);

/* QUANTIDADE DE HOMENS E MULHERES */
SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM TB_CLIENTE
GROUP BY SEXO;

SELECT C.ID_CLIENTE, C.EMAIL, C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F'
AND E.BAIRRO = 'CENTRO' 
AND E.CIDADE = 'RIO DE JANEIRO'
AND (T.TIPO = 'RES' OR T.TIPO = 'COM');

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME,C.EMAIL, T.NUMERO AS CELULAR, E.ESTADO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'RJ';

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT  C.NOME, C.EMAIL, T.NUMERO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F'
AND E.ESTADO = 'SP';

/*
 FUNCTIONS - IFNULL() 
	CASO O CAMPO PASSADO COMO PRIMEIRO PARAMETRO SEJA NULO, 
    SERÁ SUBSTITUIDO PELA MENSAGEM PASSADA NO SEGUNDO PARAMETRO DA FUNÇÃO.
*/
SELECT 
	C.NOME, 
	IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL, 
	E.ESTADO, 
	T.NUMERO 
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
	ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
	ON C.ID_CLIENTE = T.ID_CLIENTE;

/* 
	VIEW 
    
	AS VIEWS SÃO TABELAS VIRTUAIS, USE O COMANDO SHOW TABLES PARA VISUALIZAR AS VIEWS CRIADAS.
    DÊ NOMES SUGESTIVOS AS VIEWS;
*/

	/* CRIANDO VIEW */
CREATE VIEW VW_RELATORIO AS
SELECT 
	C.NOME, 
    C.SEXO,
    IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL,  
    T.TIPO,
    T.NUMERO,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E
	ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TB_TELEFONE T
	ON C.ID_CLIENTE = T.ID_CLIENTE;

	/* EXBINDO VIEWS */
SHOW TABLES; 

	/* EXIBINDO DADOS DA VIEW */
SELECT * FROM VW_RELATORIO;

    /* DELETANDO A VIEW */
DROP VIEW VIEW_RELATORIO;

	/* SELECT NA VIEW 
    OBS: CONSOME A PERFORMANCE DO BANCO
    */
SELECT NOME, EMAIL FROM VW_RELATORIO;

/* AULA 61 - OPERAÇÕES DE DML EM VIEWS - COM JOIN
INSERT E DELETE - NÃO É PERMITIDO */

/* UPDATE SÓ FUNCIONA POR LINHA DE COMANDO */
UPDATE VW_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';

/* AULA 61 - OPERAÇÕES DE DML EM VIEWS - SEM JOIN*/
CREATE TABLE TB_JOGADORES(
	ID INT,
    NOME VARCHAR(30),
    ESTADO CHAR(2)
);

INSERT TB_JOGADORES VALUES (1, 'GUERRERO', 'RS');
INSERT TB_JOGADORES VALUES (2, 'NENÊ', 'RJ');
INSERT TB_JOGADORES VALUES (3, 'RAFAEL VEIGA', 'SP');
INSERT TB_JOGADORES VALUES (4, 'VAGNER LOVE', 'PE');
INSERT TB_JOGADORES VALUES (5, 'GANSO', 'RJ');

SELECT * FROM TB_JOGADORES;

CREATE VIEW VW_JOGADORES AS
SELECT NOME, ESTADO FROM TB_JOGADORES;

SHOW TABLES;

/* SELEÇÃO */
SELECT NOME, ESTADO FROM VW_JOGADORES;

/* INSERT */
INSERT VW_JOGADORES VALUES ('LUCIO', 'PB');

/* UPDATE */
UPDATE VW_JOGADORES SET ESTADO = 'PR' WHERE NOME = 'LUCIO';

/* DELETE */
DELETE FROM VW_JOGADORES WHERE NOME = 'LUCIO';

/* AULA 62 - ORDER BY - ORDENANDO DADOS */

CREATE TABLE TB_ALUNOS(
	NUMERO INT,
    NOME VARCHAR(30)
);

INSERT INTO TB_ALUNOS VALUES (1, 'JOAO');
INSERT INTO TB_ALUNOS VALUES (1, 'MARIA');
INSERT INTO TB_ALUNOS VALUES (2, 'ZOE');
INSERT INTO TB_ALUNOS VALUES (2, 'ANDRE');
INSERT INTO TB_ALUNOS VALUES (3, 'CLARA');
INSERT INTO TB_ALUNOS VALUES (1, 'CLARA');
INSERT INTO TB_ALUNOS VALUES (4, 'MAFRA');
INSERT INTO TB_ALUNOS VALUES (5, 'JANAINA');
INSERT INTO TB_ALUNOS VALUES (1, 'JANAINA');
INSERT INTO TB_ALUNOS VALUES (3, 'MARCELO');
INSERT INTO TB_ALUNOS VALUES (4, 'GIOVANI');
INSERT INTO TB_ALUNOS VALUES (5, 'ANTONIO');
INSERT INTO TB_ALUNOS VALUES (6, 'ANA');
INSERT INTO TB_ALUNOS VALUES (6, 'VIVIANE');

/* ORDENANDO PELO CAMPO DA TABELA NUMERO */
SELECT * FROM TB_ALUNOS ORDER BY NUMERO;

/* ORDENANDO PELA POSIÇÃO DO CAMPO DA TABELA */
SELECT * FROM TB_ALUNOS ORDER BY 1;

SELECT * FROM TB_ALUNOS ORDER BY 2;

/* ORDENANDO POR MAIS DE UM CAMPO */
SELECT * FROM TB_ALUNOS ORDER BY NUMERO, NOME;

SELECT * FROM TB_ALUNOS ORDER BY 1, 2;

/* ORDENANDO ORDER BY / ASC / DESC */
SELECT * FROM TB_ALUNOS 
ORDER BY 1 ASC;

SELECT * FROM TB_ALUNOS 
ORDER BY 1 DESC;

/* 
	Aula 64 - Mudando o delimitador 
de fechamento de instrução de (;) para ($).
			
 */
 
 /* COMANDO PARA EXIBIR DETALHES DO SERVIDOR */
 STATUS 
 
/* MUDANDO O DELIMITADOR PARA ($)*/

DELIMITER $



















































