

-- Aula 36 - Filtrando Valores Nulos

USE PROJETO;

-- CLIENTES COM EMAIL NULO
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL;

-- CLIENTES COM EMAIL NÃO NULO
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;
