
-- Aula 37 - A Cláusula Update

SELECT * FROM CLIENTE;

-- JORGE | LILAN

UPDATE CLIENTE SET EMAIL = 'JORGE@GMAIL.COM' WHERE NOME = 'JORGE';

UPDATE CLIENTE SET EMAIL = 'LILIAN@OUTLOOK.COM' WHERE NOME = 'LILIAN';