
/* 6 – SOLUÇÃO: TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO
	QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO */
SELECT LIVRO, AUTOR, SEXO FROM LIVROS 
WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');

