
/* O COMANDO SELECT 
	selecao projecao e juncao
*/

SELECT NOW(); /* MOSTRA DATA E HORA */

SELECT 'WILSON DEVELOPER';

SELECT 'BANCO DE DADOS';


/* ALIAS DE COLUNAS */

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'WILSON DEVELOPER' AS ALUNO;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, EMAIL, SEXO, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;



/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;





